<?php
use setasign\Fpdi\Fpdi;

class Make_pdf extends FPDI
{
	protected $lab;
	protected $city;

	public function setLab($lab)
    {
        $this->lab = $lab;
    }

	public function setCity($city)
    {
        $this->city = $city;
    }

	public function countPages($path) {
		$pdftext = file_get_contents($path);
		$num = preg_match_all("/\/Page\W/", $pdftext, $dummy);
		return $num;
	}

	// Page header
	public function Header()
	{
	    // Logo
	    $this->Image('assets/images/log.jpg', 0, 0, 210, 298);
	    // Arial bold 15
	    $this->SetFont('Arial','B',8);
	    // Move to the right
	    $this->Cell(40);
	    // Title
	    $this->Cell(100, 480, 'Report Generated By :- '.$this->lab .', '.$this->city, 0, 0, 'C');
	}

	// Page footer
	/*function Footer()
	{
	    // Page number
	    $this->Image('logo1.png', 0, 272, 210, 25);
	}*/
}