<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<section class="about-section">
    <div class="container">
        <div class="row features">
            <div class="col-md-12">
                <h2 style="text-align: center;">LabMan Diagnostic Private Limited <br> Terms and Conditions</h2>
                <p>If you use labmandiagnostic.com to book a test, it implies that you agree to the Terms and Conditions. Please do not use the website if you do not agree with any of the terms.</p>
                <p>The content on the site labmandiagnostic.com is sole property of <b>LabMan Diagnostic Private Limited.</b> The information provided in the site is a product of intelligential of lab experts and is designed to help all the patients/customers in best possible manner. Although reliance on this information is solely up to you and any problems arising due to any error factual, logistical and/or typographical cannot be used against LabMan Diagnostic Private Limited. Labmandiagnostic.com is a platform where you can book tests from all registered diagnostic labs but it doesn’t claim to be a diagnostic center in itself. It is suggested that you contact your doctor directly if your health issues need medical intervention. We cannot be held liable for any breakdowns or faults on our site. LabMandiagnostic.com may contain links to external web sites. In no event whatsoever shall LabMandiagnostic.com be held responsible for the content, accuracy or opinions expressed in these web sites. These web sites are not monitored or checked for accuracy or completeness by us. If you decide to leave our web site and access these third-party sites, you do so at your own risk.</p>
                <p>LabMandiagnostic.com has made reasonable efforts to make this web site as timely and accurate as possible, but because errors may occur, this web site is provided as is and as available without any warranty, implied or statutory as to the operation of the web site or the information, content or materials included on the web site. To the full extent permissible by applicable law, LabMandiagnostic.com specifically disclaims any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement. In no event unless agreed to in writing will any copyright holder, or any other authorized party who gives and/or conveys the services as permitted above, be liable to you for damages, including any general, special, incidental or consequential damages arising out of the use or inability to use the services (including but not limited to loss of data or data being rendered inaccurate or losses sustained by you or third parties or a failure of the company).</p>
                <p>By agreeing to these terms and using our website which may include submission (in manner of forms, emails, suggestions, feedbacks) of any kind of information, details or facts, you grant LabMandiagnostic.com and all other persons or entities involved in the operation of the website the right to use, store and retrieve your information in connection with the operations and saving of records/data and send you timely notifications in form of Emails, SMS and posts. LabMandiagnostic.com may use any form of data for research and development purposes while still abiding by the law so as to maintain the integrity and anonymity of the user. LabMandiagnostic.com in any case shall not be liable for any claims, charges, damages, liabilities, losses and expenses of whatever nature and howsoever arising from the web site, its services or these terms and conditions, including, but not limited to compensatory, direct, indirect, incidental, special, punitive or consequential damages, arising out of the use of the website. This limitation on liability applies to, but is not limited to, the transmission of any disabling device or virus that may infect your equipment, failure or mechanical or electrical equipment or communication lines, telephone or other interconnect problems (e.g., you cannot access your internet service provider), unauthorized access, theft, bodily injury, property damage, operator errors, strikes or other problems or any act of god. Some jurisdictions do not allow the limitation or exclusion of liability. Accordingly, some of the above limitations may not apply to you.</p>
                <p>LabMandiagnostic.com reserves the right to discontinue or modify this website, temporarily or permanently, with or without notice to you. Unless explicitly stated otherwise, any new features that augment or enhance the current website shall be subject to these terms and conditions.</p>
                <h3>Grievance Officer</h3>
                <p>In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below</p>
                <p>Name : Priya Solanki <br>E-mail : priyasolanki@labmandiagnostic.com</p>
            </div>
        </div>
    </div>
</section>